create table if not exists training_type
(
    id                 bigint generated by default as identity
    primary key,
    training_type_name varchar(255)
    constraint training_type_training_type_name_check
    check ((training_type_name)::text = ANY
((ARRAY ['CARDIO'::character varying, 'STRENGTH'::character varying, 'FLEXIBILITY'::character varying])::text[]))
    );

create table if not exists users
(
    enabled boolean,
    id        bigint generated by default as identity
    primary key,
    firstname varchar(255),
    lastname  varchar(255),
    password  varchar(255),
    username  varchar(255) unique
    );


create table if not exists trainee
(
    dateofbirth date,
    id          bigint not null
    primary key
    constraint fkpx9kccl4t64wtsi8geile7vwo
    references public.users
);


create table if not exists address
(
    apartmentnumber integer not null,
    buildingnumber  integer not null,
    id              bigint generated by default as identity
    primary key,
    trainee_id      bigint
    unique
    constraint fkfea0xfdigdrjerw9jjba70ws8
    references public.trainee,
    city            varchar(255),
    street          varchar(255)
    );


create table if not exists trainer
(
    id               bigint not null
    primary key
    constraint fkd2hg6g09xsi5yyhtg5btyx13m
    references public.users,
    training_type_id bigint
    constraint fkbr9evfuc2m77pw4i65cxmm140
    references public.training_type
);


create table if not exists training
(
    trainingduration numeric(21),
    id               bigint generated by default as identity
    primary key,
    trainee_id       bigint
    constraint fki2dctw34e0xl50d8tsnrre7te
    references public.trainee,
    trainer_id       bigint
    constraint fk7r3b25ygw5bdjamojskmpk0b9
    references public.trainer,
    training_type_id bigint
    constraint fkosdbocw0x9ygfmna67s7vtewh
    references public.training_type,
    trainingname     varchar(255),
    trainingdays     varchar(255)[],
    trainingdate DATE
    );

CREATE TABLE IF NOT EXISTS authorities (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name VARCHAR(255) UNIQUE NOT NULL
    );

CREATE TABLE IF NOT EXISTS users_authorities (
                                                 user_id BIGINT NOT NULL,
                                                 authority_id BIGINT NOT NULL,
                                                 PRIMARY KEY (user_id, authority_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (authority_id) REFERENCES authorities(id) ON DELETE CASCADE
    );