
# jdbc.X
jdbc.driverClassName=org.postgresql.Driver
jdbc.test.url=jdbc:postgresql://localhost:5432/gym_test
jdbc.test.user=armine
jdbc.test.pass=0000


spring.datasource.url=jdbc:postgresql://localhost:5432/gym_test
spring.datasource.username=armine
spring.datasource.password=0000

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog-cumulative.yml


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true